FROM node:14-alpine

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app

RUN yarn

COPY . /usr/src/app

CMD ["yarn", "dev"]

# docker build -f Dockerfile.dev -t your-image-name:dev .