FROM node:14-alpine AS BUILD_IMAGE

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/

RUN yarn --frozen-lockfile

COPY . .

FROM node:14-alpine

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY --from=BUILD_IMAGE /usr/src/app ./
COPY --from=BUILD_IMAGE /usr/src/app/node_modules ./node_modules

CMD ["yarn", "dev"]

# docker build -f Dockerfile.dev -t your-image-name:dev .